"""Add is_admin and explanation

Revision ID: cee71c85c135
Revises: 
Create Date: 2026-04-11 00:22:10.076584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee71c85c135'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schemes')
    op.add_column('history', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('history', 'explanation')
    op.create_table('schemes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scheme_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('benefits', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eligibility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('application', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('documents', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('schemecategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('schemes_pkey'))
    )
    # ### end Alembic commands ###
