"""Add status and sentiment

Revision ID: f94949bdeb8b
Revises: cee71c85c135
Create Date: 2026-05-02 03:19:49.266717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94949bdeb8b'
down_revision: Union[str, Sequence[str], None] = 'cee71c85c135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('status', sa.String(), nullable=True))
    op.add_column('history', sa.Column('sentiment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'sentiment')
    op.drop_column('history', 'status')
    # ### end Alembic commands ###
